cloudposse/terraform-spacelift-cloud-infrastructure-automation

examples/complete/fixtures.tfvars, examples/complete/stacks/ue2-globals.yaml, examples/complete/stacks/ue2-testing.yaml, examples/complete/stacks/uw2-globals.yaml, main.tf, modules/stack/main.tf
* Explicitly setting `manage_state` in `complete` example since it now defaults to `false` and we need it to be `true`
* Adding support for environment globals YAML configurations
* Adding `<environment>-globals.yaml` configuration yamls to `complete` example
* Reverting change to global context attachment in stack module due to Terraform `count` error (since the variable is dependency on resource creation)
**NOTE:** Some of the new environment global variable logic is a little rough around the edges. The approach was to get this working quickly, with the expectation that we'll be replacing the YAML config parsing w/ our upcoming YAML config module in the near future.
Also, these changes have been tested in Spacelift!
=> Adding support for environment globals

README.md, examples/complete/main.tf, examples/complete/stacks/gbl-root.yaml, examples/complete/stacks/ue2-testing.yaml, examples/complete/stacks/uw2-testing.yaml, modules/environment/main.tf
- Adding support for branch override at the project/component level
- Updating the example project because a couple things were out of date!
- This will allow us to deploy Terraform from specific branches during the early development cycle (e.g. `sandbox`).
=> Adding support for branch override & updating example project

policies/push-global.rego
* Updated trigger policy to watch `*.tf.json` files
* Allow using JSON notation in terraforming code
=> Support *.tf.json files

README.md, docs/terraform.md, main.tf, modules/environment/main.tf, modules/stack/main.tf, modules/stack/variables.tf, policies/push-global.rego
- Support use of `atmos` to generate vars file
- Ignore commits with message "pre-commit fixes"
- Vars need to be up-to-date at all times during a PR lifecycle
- Pre-commit should not be making semantic changes and thus we can avoid having it trigger a second run
Supersedes and closes #15
=> Support use of atmos to generate vars file

modules/environment/main.tf, modules/stack/main.tf, modules/stack/variables.tf
- Use logical component name for Atmos
- Atmos CLI takes logical component name as argument
=> Use logical component name for Atmos

.github/CODEOWNERS, .github/workflows/validate-codeowners.yml, README.md, docs/terraform.md, main.tf, modules/environment/main.tf, modules/environment/variables.tf, modules/stack/main.tf, modules/stack/variables.tf, policies/plan-global.rego, policies/plan.rego
- Add global "plan" policy to wait for confirmation after failure
- We do not want Spacelift to steamroll past failures, which it does by default
=> Add global "plan" policy to wait for confirmation after failure

.github/auto-release.yml, README.md, docs/terraform.md, main.tf, modules/environment/main.tf, modules/environment/variables.tf, modules/stack/main.tf, modules/stack/variables.tf, variables.tf
* Add `stack_config_folder_name` variable
* The existing variable `stack_config_path` is used to read the YAML stack config using the `terraform-yaml-stack-config` module, and it needs to be a relative path to the `stacks` folder at the time of execution so the module could find the YAML config files. It's usually in the format `../../../stacks`
* On the other hand, we need to specify the name of the stack config folder to prefix the imports with it to be used in the Rego policies (it should not be a relative path to stack configs)
=> Add `stack_config_folder_name` variable

main.tf, modules/stack/main.tf, modules/stack/variables.tf
* Add `infrastructure_stack_name` variable to stack sub-module
* Spacelif stack is different from infrastructure (atmos) stack, and has different name
=> Fix spacelift atmos stack

main.tf, modules/stack/main.tf, modules/stack/variables.tf, policies/trigger-global.rego
* Update `trigger-global` policy
* Add component ENV vars to Spacelift stack ENV vars
* The updated `trigger-global` policy will trigger Spacelift stack deployment after it gets created (when `spacelift/workspace_enabled` set to `true` in the same PR that adds the stack config itself)
* YAML stack configs support the `env` section for each component, which is a map of ENV vars
```
env:
ENV_TEST_1: value1
TF_CLI_ARGS_apply: "-parallelism=1"
```
This will allow setting Terraform parameters (e.g. `-parallelism`) for each infrastructure component individually.
=> Update `trigger-global` policy. Add component ENV vars to Spacelift stack ENV vars

README.md, docs/terraform.md, policies/push-global.rego
* Updated the trigger to allow `.tpl` file changes
* We use Terraform template files and need to trigger Spacelift runs when they change
=> Add support for tpl file triggers

README.md, docs/terraform.md, main.tf, modules/stack/main.tf, modules/stack/versions.tf, policies/trigger-dependencies.rego, versions.tf
* Update `trigger-dependencies` Rego policy and attach it to all Spacelift stacks
* Update Spacelift terraform provider source and version
* The updated `trigger-dependencies` Rego policy is attached to all infrastructure stacks and will trigger other infrasctructure stacks that depend on the current stack. The other stacks must have a label `depends-on:<current_stack_name>` to be triggered after the current stack finishes running
* Labels `depends-on:<current_stack_name>` are defined in YAML stack config files and attached to each Spacelift stack by `terraform-provider-utils` (see *references*) 
* Will be used in Spacelift workflows to trigger the dependent stacks after the "parent" stacks finish running
* Update Spacelift terraform provider source and version to use the official …
=> Update `trigger-dependencies` Rego policy and attach it to all Spacelift stacks

README.md, docs/terraform.md, main.tf, modules/stack/main.tf, modules/stack/outputs.tf, modules/stack/variables.tf, variables.tf
* Add `spacelift_webhook` to each Spacelift stack
* Allow enabling/disabling webhooks per stack in YAML config files
* Allow integration between Spacelift and third-party event-collection systems (e.g. Splunk) to monitor and audit Spacelift runs
* Spacelift sends POST requests about run state changes to the webhook endpoint  
* https://registry.terraform.io/providers/spacelift-io/spacelift/latest/docs/resources/webhook
* https://github.com/spacelift-io/terraform-provider-spacelift#spacelift_webhook-resource
=> Add `spacelift_webhook` to each stack. Allow enabling/disabling webhooks per stack

main.tf
* Fix `spacelift_webhook`
* `webhook_endpoint` is optional
* If `webhook_endpoint` is not defined in YAML config nor in `var.webhook_endpoint`, `coalesce` is not working and the following error gets thrown:
```
webhook_endpoint = coalesce(try(each.value.settings.spacelift.webhook_endpoint, null), var.webhook_endpoint)
|----------------
| each.value.settings.spacelift is object with 1 attribute "workspace_enabled"
| var.webhook_endpoint is null
Call to function "coalesce" failed: no non-null, non-empty-string arguments.
```
=> Fix `spacelift_webhook`

modules/stack/main.tf
* use `count` instead of `enabled` in `resource "spacelift_webhook"`
* Even if `enabled` is set to `false` , the Spacelift provider still looks at the `endpoint` and complains if it's not provided
=> use `count` instead of `enabled` in `resource "spacelift_webhook"`

policies/push-global.rego
* Adds `.yml` to tracked extensions in the global push policy. 
* Adds `startswith(affected_files[_], deps[_])` to `stack_config_affected`
* Enables support for both yaml file extensions: `yml` + `yaml`
* Allows `deps` labels to be a directory such as `deps:config/` or `deps:lambda_src/` and still get picked up as a change
* N/A
=> feat: adds .yml to push-global tracked_extensions to support both yamls

README.md, docs/terraform.md, main.tf, variables.tf
* Enable custom external Rego policies per Spacelift stack
* Allow specifying custom Rego policies by names in YAML stack configs
* The callers of the module can define their own `catalog` of various custom Rego policies and use them to attach to different stacks
* For example, the caller might have a set of custom Rego `ACCESS` policies (with different names, e.g. `access.dms-prod.rego`, `access.dms-dev.rego`) to allow only particular teams/users to access specific Spacelift stacks to provision specific resources
=> Enable custom external Rego policies per Spacelift stack

README.md, docs/terraform.md, main.tf, modules/stack/main.tf, modules/stack/variables.tf, variables.tf
* Add drift detection for administrative stack and per infrastructure stack
* Allow enabling/disabling, automatic reconciliation, and `cron` schedules per infrastructure stack in YAML config
* Spacelift will create drift detection runs (proposed runs) based on the `cron` schedules
* If drift is detected and `reconcile` is turned on, it will create a tracked run to correct the drift
* If `reconcile` is off, then you can subscribe to drift notifications through the run state changed webhooks
* Drift detection only works on private worker pools and if no tracked runs are pending on the stack
* Drift detection/reconciliation runs behave like normal runs, so they respect plan policies, initialization policies, autodeploy, etc.
=> Add drift detection for administrative stack and per infrastructure stack

README.md, docs/terraform.md, examples/complete/versions.tf, main.tf, modules/stack/main.tf, modules/stack/outputs.tf, modules/stack/variables.tf, modules/stack/versions.tf, variables.tf, versions.tf
* Add `spacelift_stack_destructor` and `spacelift_aws_role` resources
* `spacelift_stack_destructor` enables destroying the resources of a stack before deleting the stack itself (configurable per stack in YAML config)
* `spacelift_aws_role` represents cross-account IAM role delegation between the Spacelift worker and an individual stack. If this is enabled, Spacelift will use AWS STS to assume the supplied IAM role and put its temporary credentials in the runtime environment (configurable per stack in YAML config)
* https://registry.terraform.io/providers/spacelift-io/spacelift/latest/docs/resources/stack_destructor 
* https://registry.terraform.io/providers/spacelift-io/spacelift/latest/docs/resources/aws_role
=> Add `spacelift_stack_destructor` and `spacelift_aws_role` resources

catalog/policies/git_push.default.rego
* Update Git push policy
* Propose a run (shown in the "PR" tab in Spacelift UI) if YAML stack config dependencies are affected by the push (before, proposed runs were triggered only when the component's files were changed)
=> Update Git push policy

catalog/policies/git_push.head-diff.rego
* Fix Git Push `head_diff` policy
* `head_diff` is in `input`, not in `input.push`
=> Fix Git Push `head_diff` policy

catalog/policies/git_push.proposed-run.rego, catalog/policies/git_push.tracked-run.rego
* Fix Git push policies
* Remove `ignore` block from the Git Push policies 
* We already provide `propose` and `track` block which have all the required logic to evaluate if a proposed a tracked run needs to be started
* The `ignore` block is redundant in the policies, since it uses the same (but opposite) logic as the `propose` and `track `block
* Having the `ignore` block in the two Git Push policies prevents a run from being triggered in some cases (e.g. when pushing directly to the default/tracked branch, the `ignore` block in the `git_push.propose-run.rego` policy prevents the traked run from being triggered in the `git_push.tracked-run.rego` policy
```
The policy may define boolean track, propose and ignore rules. 
The positive outcome of at least one ignore rule causes the push to …
```
=> Fix Git Push policies. Remove `ignore` block from the Git Push policies 

main.tf
* Remove `coalesce` from `commit_sha` argument
Both arguments are either null or empty which causes the error:
```
│ Error: Error in function call
│ 
│   on .terraform/modules/spacelift/main.tf line 58, in module "stacks":
│   58:   commit_sha            = coalesce(try(each.value.settings.spacelift.commit_sha, null), var.commit_sha)
│     ├────────────────
│     │ each.value.settings.spacelift is object with 1 attribute "workspace_enabled"
│     │ var.commit_sha is null
│ 
│ Call to function "coalesce" failed: no non-null, non-empty-string
│ arguments.
```
https://github.com/cloudposse/terraform-spacelift-cloud-infrastructure-automation/blob/7a306ca1d80fd3cc32fb0db9e53b9ded16e73012/main.tf#L58
The fix is to remove the `coalesce` statement.
* Previous PR …
=> Remove `coalesce` from `commit_sha` argument

main.tf
* Add `count` to `spacelift_policy.trigger_administrative`
* If we disable `administrative_trigger_policy_enabled`, it will still create the `spacelift_policy` but won't attach it. This change will make sure it won't create the policy either.
N/A
=> Add `count` to `spacelift_policy.trigger_administrative`

README.md, docs/terraform.md, variables.tf
* Removes the unused `*_policy_id` vars
* They are no longer used and have been deprecated via the newer, convention based policy assignment scheme. 
* N/A
=> fix: removes unused, deprecated vars

README.md, docs/terraform.md, main.tf, modules/stack/main.tf, modules/stack/variables.tf, variables.tf
* Add administrative
* Be able to create administrative stacks by updating a boolean
* This would be necessary if we needed to create an service specific admin stack for its preview environment
* This also opens up managing administrative stacks by using the `modules/stack` module directly
N/A
=> Add administrative

README.md, docs/terraform.md, main.tf, modules/stack/main.tf, modules/stack/variables.tf, variables.tf, versions.tf
* Adds support for Spacelift Context attachments: https://registry.terraform.io/providers/spacelift-io/spacelift/latest/docs/resources/context_attachment
* Bumps Spacelift provider required version to `>= 0.1.2` (latest)
* Enables sharing many variables easily across many Spacelift Stacks.
* Provider version bump is due to the `before_*` (and friends) arguments as they error out when utilizing an older provider version (`0.0.4` I'd guess). See 
* N/A
=> feat: adds support for attaching contexts + bumps provider version

catalog/policies/git_push.default.rego, catalog/policies/git_push.head-diff.rego, catalog/policies/git_push.proposed-run.rego, catalog/policies/git_push.tracked-run.rego
* Update `proposed-run` Rego push policy
* Don't ignore a commit with the message `pre-commit fixes`  because we use `rennovatebot` which pushes commits on which we want to trigger Spacelift stacks
* Ignore if the PR has the label `spacelift-no-trigger` - useful if we need to test and push many commits to the PR but don't want to trigger Spacelift stacks (especially if the commits affects many global files which in turn triggers many Spacelift stacks)
=> Update `proposed-run` Rego push policy

README.md, README.yaml, catalog/policies/git_push.default.rego, catalog/policies/git_push.proposed-run.rego
* Add canceling runs if new commits are pushed
* No use in planning spacelift stacks for older commits. We might as well cancel stacks that are queued and only plan the newer stacks.
* Purposely not added to `git_push.default` because that is a deprecated rego policy
* https://docs.spacelift.io/concepts/policy/git-push-policy#canceling-in-progress-runs
=> Add canceling runs if new commits are pushed

.github/auto-release.yml, LICENSE, README.md, main.tf
* Fix Spacelift stacks context filters
* In terraform, both sides of the OR operator are always evaluated
* When provisioning Spacelift stacks for clients that don't use `tenant`, the module threw the error
```
Error: Unsupported attribute
on .terraform/modules/spacelift/main.tf line 30, in locals:
30:     (lookup(var.context_filters, "tenants", null) == null || contains(lookup(var.context_filters, "tenants", 
[v.vars.tenant]), v.vars.tenant)) &&
|----------------
| v.vars is object with 4 attributes
This object does not have an attribute named "tenant".
```
* Use `lookup` with a default to prevent these errors
=> Fix Spacelift stacks context filters

README.md, README.yaml, modules/stack/main.tf
Always create `spacelift_stack_destructor` resource; toggle stack destructor functionality via `deactivated` attribute in `spacelift_stack_destructor`, rather than the `count` meta-attribute (see below on reason why).
The `spacelift_stack_destructor` resource is a special resource which, when deleted, will delete all resources in the stack:
https://github.com/spacelift-io/terraform-provider-spacelift/blob/6b9411707f6243ffa956e06bdaa1659820250c35/spacelift/resource_stack_destructor.go#L78-L104
Because of this, `var.stack_destructor_enabled` should not toggle the creation or destruction of this resource, since toggling it from `true` to `false` with the intention of disabling the stack destructor functionality will result in all of the resources in the stack being deleted. Instead, this …
=> Fix: Properly Toggle Stack Destructor Functionality via `var.stack_destructor_enabled`

.github/workflows/auto-context.yml, .github/workflows/auto-format.yml, .github/workflows/auto-readme.yml, .github/workflows/chatops.yml, .github/workflows/validate-codeowners.yml, catalog/policies/git_push.proposed-run.rego
* Check branch matches for proposed policy
* Prevent PR 1 from stomping over queued stack runs in PR 2
* We previously used upstream docs policy but it did not check the input branch https://docs.spacelift.io/concepts/policy/git-push-policy#canceling-in-progress-runs
=> Check branch matches for proposed policy

catalog/policies/git_push.proposed-run.rego
* Ignore spacelift runs on draft PRs
* Waiting on team feedback
* Reduce noise
* N/A
Draft
<details><summary>This has `draft: true` and `labels: ["spacelift-trigger"]` so it should run spacelift</summary>
```json
{
"in_progress": [],
"pull_request": {
"action": "merged",
"action_initiator": "nitrocode",
"author": "nitrocode",
"base": {
"author": "nitrocode",
"branch": "main",
"created_at": 1651002899000000000,
"hash": "fdd4011c23a012b358eacec4bbf4143aa97cdae2",
"message": "snip"
},
"diff": ["components/terraform/ses/README.md", "components/terraform/ses/main.tf", "components/terraform/ses/variables.tf", "stacks/catalog/ses.yaml"],
"draft": true,
"head": {
"author": "nitrocode",
"branch": "ses-spacelift",
"created_at": 1651071679000000000,
"hash": …
```
=> Ignore spacelift runs on draft PRs

catalog/policies/git_push.proposed-run.rego
* Fix unignored draft prs
* There is an issue if a draft PR has zero PR labels, the push proposed policy will still trigger a plan
* This will explicitly set an ignore on both conditions: 1) if draft and no spacelift-trigger label and 2) if draft and no labels
N/A
=> Fix unignored draft prs if no pr labels

main.tf
* Add more settings - policies by id to stack
* Add more settings - custom runner image per stack
* Add more settings - manage state per stack
*  policies by id to stack - In order to add custom policies per stack
This is also a nice escape hatch. If we enable `external_execution` on the admin stacks, they will not create the global trigger policy or attach it. If we create the global trigger policy using the first admin stack's `policies_available = ["trigger.administrative"]`, then a spacelift setting's `policies_by_id_enabled = ["trigger-administrative-policy"]` can still attach it.
* custom runner image per stack - in case we need to test out a custom runner per stack, such as the official spacelift runner + atmos + spacelift related shell scripts
* manage_state - in case we need to …
=> Add more settings - policies by id to stack

catalog/policies/git_push.proposed-run.rego
> We try to translate that into a common language for all VCS providers.
> So in our lingo that’s “draft”.
> Regardless of whether you’re using GitHub, GitLab or Azure DevOps (Bitbucket doesn’t have that concept).
And this is why we aren't using something like a github specific event i.e. `converted_to_draft` or `ready_for_review`
* To allow draft or non draft events to toggle proposed stacks
* Thank you @marcinwyszynski from Spacelift 
* Pull request actions (draft is undocumented) https://docs.spacelift.io/concepts/policy/git-push-policy#data-input
* https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#webhook-payload-object-34
* https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
=> Allow draft actions in proposed

main.tf
* Fixing `policies_by_name_enabled` logic by replacing `var.policies_by_name_enabled` with empty list
* Because `var.policies_by_name_enabled` currently doesn't do anything!
=> Fixing policies_by_name_enabled logic

.editorconfig, catalog/policies/git_push.proposed-run.rego, catalog/policies/git_push.proposed-run_test.rego
* Add git push proposed run test
* Explicitly added a *.rego space policy
* This is a large policy and it should be tested if any new changes are introduced
* Consistency
* 100% coverage of `git_push.proposed-run.rego`
* N/A
```
$ opa test git_push.proposed-run.rego git_push.proposed-run_test.rego -v
git_push.proposed-run_test.rego:
data.spacelift.test_propose_project_root_affected: PASS (790.886µs)
data.spacelift.test_propose_stack_config_affected_imports_label: PASS (404.527µs)
data.spacelift.test_propose_stack_config_affected_deps_label: PASS (586.646µs)
data.spacelift.test_propose_stack_config_affected_stack_name_root_stack: PASS (419.415µs)
data.spacelift.test_propose_stack_config_affected_stack_stack_label: PASS (437.601µs) …
```
=> Add git push proposed run test

.github/auto-release.yml, .github/workflows/validate-codeowners.yml, Makefile, README.md, main.tf
- Add dependencies so new policies can be referred to by ID
- Removes the need to refer to policies by name during initial creation
=> Policy dependencies

README.md, docs/terraform.md, main.tf, modules/stack/main.tf, modules/stack/variables.tf, variables.tf
* Ability to create a dedicated space for any stack via it's Spacelift settings (although it's primarily meant for admin stacks)
* Ability to override space id for attachments (policies, contexts, etc.) for when we need to put them in a space separate from the admin stack (e.g. `root`)
* Ability to override space id for stacks created by an admin stack (`stacks_space_id`)
* Ability to specify space inheritance
* Should default to `legacy` space everywhere so as to not break existing users who haven't migrated to spaces
* This was tested successfully w/ a CP client
* Also tested a legacy setup by running a plan on `cplive` and verifying nothing is broken
=> Adding support for Spaces

main.tf
- Allow overriding the display stack name using yaml
- Some users want specific names due to prior documentation or readability.
- Using `stack_name_pattern` would override the spacelift stack slug which would recreate the stack which we do not want to do.
- By supplying `stack_name` we can retain the slug (avoid recreation) and change the display name to what we want
N/A
=> Allow overriding the display stack name using yaml

main.tf
* Add a spacelift space_id override
* At the moment, we have an admin infra stack that creates an infra space. The admin infra stack also creates a spacelift-policy stack which requires the root space. This will allow the spacelift-policy stack to override the infra space to use the root space.
N/A
=> Add a spacelift space_id override

catalog/policies/push.git_comment.rego
Update the order of comments from /spacelift {preview,deploy} [stackname] to /spacelift [stackname] {preview,deploy}
When there are stacks whose ids are substrings of other stacks, both stacks were accidentally triggered because the spacelift policy uses contains(input.pull_request.comment, concat(" ", ["/spacelift", "preview", input.stack.id])) to match the comments from the Pull Request.
[cloudposse/github-action-atmos-affected-trigger-spacelift](https://github.com/cloudposse/github-action-atmos-affected-trigger-spacelift/pull/26) PR
=> update policy based on new command ordering
